<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <!-- Include Terminal -->
    <!-- <OutputType>Exe</OutputType> -->
     <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
	  <GenerateAssemblyInfo>false</GenerateAssemblyInfo>
	  <GenerateTargetFrameworkAttribute>false</GenerateTargetFrameworkAttribute>
	  <Platforms>AnyCPU;x64;x86</Platforms>
  </PropertyGroup>

  <!-- Packages -->
  <ItemGroup>
    <PackageReference Include="Newtonsoft.Json" Version="13.0.1" />
  </ItemGroup>

  <PropertyGroup>
    <!-- Fixes differences between cultures -->
    <InvariantGlobalization>true</InvariantGlobalization>
    <!-- Allow Unsafe for Raylib -->
    <AllowUnsafeBlocks>True</AllowUnsafeBlocks>
  </PropertyGroup>

  <!-- Icons -->
  <!-- <PropertyGroup>
    <ApplicationIcon>Icon.ico</ApplicationIcon>
  </PropertyGroup>

  <ItemGroup>
    <None Remove="Icon.ico" />
    <None Remove="Icon.bmp" />
  </ItemGroup>

  <ItemGroup>
    <EmbeddedResource Include="Icon.ico" />
    <EmbeddedResource Include="Icon.bmp" />
  </ItemGroup> -->

  <ItemGroup>
    <ProjectReference Include="_Raylib-cs\Raylib-cs.csproj" />
  </ItemGroup>
</Project>